INSERT INTO station (id, name) VALUES (1, 'Abrantes');
INSERT INTO station (id, name) VALUES (2,'Adémia');
INSERT INTO station (id, name) VALUES (3,'Afife');
INSERT INTO station (id, name) VALUES (4,'Agualva-Cacém');
INSERT INTO station (id, name) VALUES (5,'Aguda');
INSERT INTO station (id, name) VALUES (6,'Aguim');
INSERT INTO station (id, name) VALUES (7,'Albufeira-Ferreiras');
INSERT INTO station (id, name) VALUES (8,'Alcaçovas');
INSERT INTO station (id, name) VALUES (9,'Alcaide');
INSERT INTO station (id, name) VALUES (10,'Alcains');
INSERT INTO station (id, name) VALUES (11,'Alcântara-Mar');
INSERT INTO station (id, name) VALUES (12,'Alcântara-Terra');
INSERT INTO station (id, name) VALUES (13,'Alcaria');
INSERT INTO station (id, name) VALUES (14,'Aldeia');
INSERT INTO station (id, name) VALUES (15,'Alegria');
INSERT INTO station (id, name) VALUES (16,'Alfarelos');
INSERT INTO station (id, name) VALUES (17,'Alferrarede');
INSERT INTO station (id, name) VALUES (18,'Algés');
INSERT INTO station (id, name) VALUES (19,'Algoz');
INSERT INTO station (id, name) VALUES (20,'Algueirão');
INSERT INTO station (id, name) VALUES (21,'Alhandra');
INSERT INTO station (id, name) VALUES (22,'Alhos Vedros');
INSERT INTO station (id, name) VALUES (23,'Almourol');
INSERT INTO station (id, name) VALUES (24,'Alpedrinha');
INSERT INTO station (id, name) VALUES (25,'Alvarães');
INSERT INTO station (id, name) VALUES (26,'Alvega-Ortiga');
INSERT INTO station (id, name) VALUES (27,'Alverca');
INSERT INTO station (id, name) VALUES (28,'Alvito');
INSERT INTO station (id, name) VALUES (29,'Amadora');
INSERT INTO station (id, name) VALUES (30,'Ameal');
INSERT INTO station (id, name) VALUES (31,'Aregos');
INSERT INTO station (id, name) VALUES (32,'Areia-Darque');
INSERT INTO station (id, name) VALUES (33,'Arentim');
INSERT INTO station (id, name) VALUES (34,'Areosa');
INSERT INTO station (id, name) VALUES (35,'Arronches');
INSERT INTO station (id, name) VALUES (36,'Assumar');
INSERT INTO station (id, name) VALUES (37,'Avanca');
INSERT INTO station (id, name) VALUES (38,'Aveiro');
INSERT INTO station (id, name) VALUES (39,'Aveleda');
INSERT INTO station (id, name) VALUES (40,'Azambuja');
INSERT INTO station (id, name) VALUES (41,'Baixa da Banheira');
INSERT INTO station (id, name) VALUES (42,'Barragem de Belver');
INSERT INTO station (id, name) VALUES (43,'Caldas da Rainha');
INSERT INTO station (id, name) VALUES (44,'Caldas de Moledo');
